# **NumPy Arrays**

The basic difference NumPy and List is that the NumPy Array will contain only homogenous elements while in case of lists values of different datatypes can be stored.

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
mat = np.array(matrix)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Methods of NumPy**
# .arange()
It creates numeric sequence of evenly spaced numeric values within an interval.

**Syntax: np.arange()**

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(0,13,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12])

## .zeros()

Generates array of 0s. If one parameter is passed it will create 1-D array of that much size. If we pass a tuple, it will create 2-D array, the first being number of rows and second being the number of columns.

**Syntax: np.zeros()**

In [ ]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.zeros((4,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## .ones()

Works same as .zeros() with only difference being the elements are 1s instead of 0s

**Syntax: np.ones()**

In [ ]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

## .linspace()

.arange() creates range of number from start to end separated by a stepsize, defaulted to 1. In .linspace() instead of stepsize, we specify how many elements we want and numpy will create evenly spaced items between the start and end number.

**Syntax: np.linspace(start,stop,no_of_elements)**

In [ ]:
arr = np.linspace(1,3,50)
arr

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [ ]:
arr = np.linspace(4,5,7)
arr

array([4.        , 4.16666667, 4.33333333, 4.5       , 4.66666667,
       4.83333333, 5.        ])

## .eye()

It creates an identity matrix by taking a single parameter.

**Syntax: np.eye(size_of_square_matrix)**

In [ ]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

# **Creating array of random numbers**

## .rand()

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
import numpy as np

In [ ]:
np.random.rand(4) #creates an array containing random numbers between 0 and 1(exclusive) of size 4

array([0.46135233, 0.85867892, 0.78330336, 0.81225633])

In [ ]:
np.random.rand(2)

array([0.44329503, 0.14212728])

In [ ]:
np.random.rand(2,3) #creates an 2D array containing random numbers between 0 and 1(exclusive) of size 2x3

array([[0.79304156, 0.28475079, 0.93256205],
       [0.4295682 , 0.48555361, 0.84032496]])

## .randn()

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform.

In [ ]:
np.random.randn(3)

array([-0.39846546,  0.66792509, -0.19591138])

In [ ]:
np.random.randn(3,4)

array([[-0.33289766, -1.82653136,  0.76030998,  1.26975173],
       [-0.66186054,  0.84049625, -0.62441963, -0.79771535],
       [ 0.73001993, -0.47000712, -1.11551783,  0.74289504]])

## .randint()

Return random integers from low (inclusive) to high (exclusive).

In [ ]:
np.random.randint(1,20,4)

array([19,  3,  8,  3])

In [ ]:
np.random.randint(1,30,8)

array([10, 18, 19,  2,  3, 19, 19,  1])

## .reshape()

It reshapes the array into different size matrix. The only condition is that total size of the array should match with the size of matrix.

In [ ]:
arr = np.random.randint(1,50,10)
arr

array([38, 41, 14, 13, 28, 29, 23, 40,  6, 27])

In [ ]:
arr.reshape(2,5)

array([[38, 41, 14, 13, 28],
       [29, 23, 40,  6, 27]])

In [ ]:
arr.reshape(5,2)

array([[38, 41],
       [14, 13],
       [28, 29],
       [23, 40],
       [ 6, 27]])

## .max() .min() .argmax() .argmin()

.max() returns the maximum element present in the array containing random numbers.

.min() returns the minimum element present in the array containing random numbers.

.argmax() returns the index of maximum element

.argmin() returns the index of minimum element

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,100,10)
arr

array([51, 69, 46, 59, 91, 49, 94, 67, 90, 20])

In [ ]:
arr.max()

94

In [ ]:
arr.min()

20

In [ ]:
arr.argmax()

6

In [ ]:
arr.argmin()

9

## .shape

Returns the size of the array or the matrix

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,50,16)
arr

array([20, 23, 43, 11, 32, 22, 40, 30, 21, 12, 44, 48, 46, 34, 31, 27])

In [ ]:
arr.shape

(16,)

In [ ]:
arr = arr.reshape(4,4)
arr

array([[20, 23, 43, 11],
       [32, 22, 40, 30],
       [21, 12, 44, 48],
       [46, 34, 31, 27]])

In [ ]:
arr.shape

(4, 4)

In [ ]:
arr = arr.reshape(2,8)
arr

array([[20, 23, 43, 11, 32, 22, 40, 30],
       [21, 12, 44, 48, 46, 34, 31, 27]])

In [ ]:
arr.shape

(2, 8)

In [ ]:
arr.dtype

dtype('int64')

# **Array Indexing**

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(2,15)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr[4]

6

In [ ]:
arr[2:7]

array([4, 5, 6, 7, 8])

In [ ]:
arr[:8]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[4:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr[:5] = 20
arr

array([20, 20, 20, 20, 20,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
slice_arr = arr[3:9]
slice_arr

array([20, 20,  7,  8,  9, 10])

In [ ]:
arr = np.random.randint(2,20,12)
arr

array([ 4, 14, 17, 12, 10,  7,  9, 17,  6,  9, 10, 17])

In [ ]:
slice_arr =  arr[3:9]
slice_arr

array([12, 10,  7,  9, 17,  6])

In [ ]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([  4,  14,  17, 100, 100, 100, 100, 100, 100,   9,  10,  17])

In [ ]:
array_2 = np.random.randint(1,50,12)
array_2

array([20, 41,  9, 45, 15, 42, 33, 32, 42, 31, 12, 28])

In [ ]:
array_2 = array_2.reshape(3,4)
array_2

array([[20, 41,  9, 45],
       [15, 42, 33, 32],
       [42, 31, 12, 28]])

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[0][2]

3

In [ ]:
matrix[1,2]

6

In [ ]:
matrix[1]

array([4, 5, 6])

In [ ]:
matrix[1:2,:1]

array([[4]])

In [ ]:
matrix[1:2]

array([[4, 5, 6]])

In [ ]:
matrix[:1]

array([[1, 2, 3]])

In [ ]:
arr = np.arange(3,14)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
boolean = arr > 7
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr[boolean]
arr

array([ 8,  9, 10, 11, 12, 13])

#**EXERCISE**

### Create a matrix of size 50 of any resolution and grab some chunks of elements.

In [ ]:
original_arr = np.arange(50).reshape(5,10)
original_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#If I want to grab 13 14 15 23 24 25
original_arr[1:3,3:6]

array([[13, 14, 15],
       [23, 24, 25]])

#NumPy Operations

*   **Array with Array**
*   **Array with Scalars**
*   **Universal Array Functions**


In [ ]:
import numpy as np

In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Array with Array**

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

## **Array with Scalars**

In [ ]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [ ]:
arr ** 2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

## **Array Universal Functions**

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])